[package]
name = "roux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.1"
poem = { version = "2.0.1", features = [] }
tokio = { version = "1.36.0", features = ["full"] }
